
title: Mon portfolio
url: 'https://charlesgdn.github.io/PortFolio'
baseurl: '/PortFolio' #change it according to your repository name



# Profile information
yourname: Charles Gandon  ## put your name
title: Ingénieur Cyber-sécurité  ## your title
location: Rennes, France


## Social Profiles
linkedin: https://www.linkedin.com/in/charles-gandon/  ## your linkedin account url




# Update all the sections by editing the files inside _includes folder.
